In [2]:
import numpy as np
from scipy.sparse import csr_matrix

# Define a simple 3x4 dense matrix
dense_matrix = np.array([
    [1, 0, 0, 4],
    [0, 5, 0, 0],
    [7, 0, 8, 0]
])

# Convert the dense matrix to a CSR (Compressed Sparse Row) format
sparse_matrix = csr_matrix(dense_matrix)

# Display the dense matrix
print("Dense Matrix:")
print(dense_matrix)

# Display the sparse matrix data
print("\nSparse Matrix Data:")
print(sparse_matrix.data)

# Display the indices of the non-zero elements (column indices)
print("Sparse Matrix Column Indices:")
print(sparse_matrix.indices)

# Display the index pointer for the beginning of each row (index pointer for each row)
print("Sparse Matrix Row Pointers (indptr):")
print(sparse_matrix.indptr)

# Display the sparse matrix in dense format (to verify correctness)
print("\nReconstructed Dense Matrix from Sparse:")
print(sparse_matrix.toarray())


Dense Matrix:
[[1 0 0 4]
 [0 5 0 0]
 [7 0 8 0]]

Sparse Matrix Data:
[1 4 5 7 8]
Sparse Matrix Column Indices:
[0 3 1 0 2]
Sparse Matrix Row Pointers (indptr):
[0 2 3 5]

Reconstructed Dense Matrix from Sparse:
[[1 0 0 4]
 [0 5 0 0]
 [7 0 8 0]]
